version: '3'
services:
  <%= projectName %>-rstudio-server:
    container_name: <%= projectName %>-rstudio-server
    build:
      context: .
      dockerfile: Dockerfile
    image: <%= projectName %>-rstudio-server-image
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio/<%= projectName %>
      - ~/Library/ApplicationSupport/renv:/home/rstudio/.local/share/renv
    working_dir: /home/rstudio
    entrypoint:
      - /usr/lib/rstudio-server/bin/rserver
    command:
      - --server-daemonize=0
      - --server-app-armor-enabled=0
    environment: 
      - USER=rstudio
      - PASS=rstudio
    stdin_open: true
    tty: true
    restart: always